# -*- coding: utf-8 -*-
"""project_one-GDP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BXb99NubwQbxoJLAQrZnDO3krRCP6psT

# DATA VISUALIZATION USING PANDAS AND MATPLOTLIB.


---
---

## Importing pandas and matplotlib library
"""

import pandas as pd
import matplotlib.pyplot as plt

"""## Importing csv file"""

df=pd.read_csv('India_GDP_Data.csv')

df

# sorting data in ascending order

df.sort_values('Year',ascending=True,inplace=True)

df

# getting info about dataset

df.shape

"""## Data cleaning"""

# checking for empty cells

df.info()

df.isnull().sum()

# checking for duplicate cells
df.duplicated().sum()

"""---
 > **since there is no null values in any of the columns, there is no need to remove or replace the empty cells.**


>likewise there is no 

>*   data in wrong format
*   duplicate data.






 ---

# Statisical Description
"""

df.describe().T

"""## Finding Correlation"""

df.corr()

"""---

### important observation from the above is
 * GDP depends on both `year` and `Per capita` and increses as both increases.
 *  likewise "Per Capita" depends on both `year` and `GDP`
 *  but "Percentage growth" doesn't depend much on any factors. so there is not much variations with respect to other factors.  

 ---



   
"""

df

"""# DATA VISUALIZATION

LINE PLOTTING
"""

# GDP Plot
plt.figure(figsize=(12,6))
plt.plot(df["Year"],df["GDP_In_Billion_USD"],color="orange")
plt.title('Year vs GDP',color='green',size=20,family='serif')
plt.xlabel('Year',color='green',size=12,family='serif')
plt.ylabel('GDP(in Billion USD',color='green',size=12,family='serif')
plt.show()

""" From the above plot, `GDP` increases as the `Year` gets increases
 

---
"""

#Per Capita Plot
plt.figure(figsize=(12,6))
plt.plot(df['Year'],df['Per_Capita_in_USD'],'-b')
plt.title('Year vs Per Capita',size=20,family='serif',color = "red")
plt.xlabel("Year",size=12,color='red')
plt.ylabel('Per Capita(in USD)',size=12,color='red')
plt.show()

"""From the above plot,`Per Capita` increases with increase in `Year`

---
"""

# percentage growth plot
plt.figure(figsize=(12,6))
plt.plot(df["Year"],df["Percentage_Growth "],'-g')
plt.title('Year vs Percentage Growth',size=20,family='serif',color = "orange")
plt.xlabel('Year',size=12,color='orange')
plt.ylabel('Percentage Growth',size=12,color='orange')
plt.show()

"""From the above plot, the `percencentage growth` does not depend on `Year` and `Percentage Growth` keeps on flactuating throughout years.

---


"""

plt.figure(figsize=(20,5))


#GDP Plot
plt.subplot(1,3,1)
plt.plot(df["Year"],df["GDP_In_Billion_USD"],color="orange")
plt.title('Year vs GDP',color='green',size=20,family='serif')
plt.xlabel('Year',color='green',size=12,family='serif')
plt.ylabel('GDP(in Billion USD',color='green',size=12,family='serif')

#Per Capita Plot
plt.subplot(1,3,2)
plt.plot(df['Year'],df['Per_Capita_in_USD'],'-b')
plt.title('Year vs Per Capita',size=20,family='serif',color = "red")
plt.xlabel("Year",size=12,color='red')
plt.ylabel('Per Capita(in USD)',size=12,color='red')

# percentage growth plot
plt.subplot(1,3,3)
plt.plot(df["Year"],df["Percentage_Growth "],'-g')
plt.title('Year vs Percentage Growth',size=20,family='serif',color = "orange")
plt.xlabel('Year',size=12,color='orange')
plt.ylabel('Percentage Growth',size=12,color='orange')

plt.suptitle('LINE PLOT',size=20,family='serif')
plt.show()

df.corr()

"""---
BOXPLOT
"""

plt.figure(figsize=(20,8))
plt.suptitle('BOX PLOT',size=20,color="k")

# GDP
plt.subplot(1,3,1)
plt.boxplot(df['GDP_In_Billion_USD'])
plt.title('GDP_In_Billion_USD',size=20,family='serif',color = "orange")

# Per Capita
plt.subplot(1,3,2)
plt.boxplot(df['Per_Capita_in_USD'])
plt.title('Per_Capita_in_USD',size=20,family='serif',color = "blue")

# Percentage Growth
plt.subplot(1,3,3)
plt.boxplot(df['Percentage_Growth '])
plt.title('Percentage_Growth ',size=20,family='serif',color = "green")

plt.show()

"""

> From the above `Boxplots`, the median, the IQR(Interquartile Range) and outliers can be visualised.

---

HISTOGRAM
"""

df.columns

plt.figure(figsize=(18,5))
plt.suptitle('HISTOGRAM',size=20,family='serif')

# GDP 
plt.subplot(1,3,1)
plt.hist(df['GDP_In_Billion_USD'],color="orange")
plt.title('GDP(in Billion USD)',color="orange",size=15,family='serif')

# Per Capita
plt.subplot(1,3,2)
plt.hist(df['Per_Capita_in_USD'],color='blue')
plt.title('Per Capita(in USD)',color='blue',size=15,family='serif')

# Percentage Growth
plt.subplot(1,3,3)
plt.hist(df['Percentage_Growth '],color='green')
plt.title('Percentage Growth',color='green',size= 15,family='serif')

plt.show()

"""> From the above `HISTOGRAM`, the values with highest and lowest frequency of particular range can be visualised.

---

SCATTER PLOT
"""

# scatter plotting for 'YEAR' vs 'GDP and Per Capita'

plt.figure(figsize=(18,7))
plt.scatter(df['Year'], df['GDP_In_Billion_USD'],color='orange',marker='p')
plt.scatter(df['Year'], df['Per_Capita_in_USD'],color='green',marker='x')
plt.title("SCATTER PLOT",size=20,family='serif')
plt.xlabel('Year',size=15,color='blue')
plt.ylabel('GDP and Per Capita',size=15,color='blue')
plt.legend(["GDP_In_Billion_USD",'Per_Capita_in_USD'])
plt.grid(color='blue')
plt.show()

"""> This `SCATTER PLOT` shows the relation between `YEAR` vs `GDP and Per Capita`.

 ---

---
---

### Conclusion
 >A dataset is imported,cleaned and visualized using `PANDAS` and `MATPLOTLIB`

 ---
 ---
"""
